/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ApiBookmarksRouteImport } from './routes/api/bookmarks'
import { Route as ApiBookmarkFoldersRouteImport } from './routes/api/bookmark-folders'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiXConnectRouteImport } from './routes/api/x/connect'
import { Route as ApiXCallbackRouteImport } from './routes/api/x/callback'
import { Route as ApiXBookmarksRouteImport } from './routes/api/x/bookmarks'
import { Route as ApiGithubStarsRouteImport } from './routes/api/github/stars'
import { Route as ApiGithubReposRouteImport } from './routes/api/github/repos'
import { Route as ApiGithubItemsRouteImport } from './routes/api/github/items'
import { Route as ApiBookmarksSearchRouteImport } from './routes/api/bookmarks.search'
import { Route as ApiBookmarksAskRouteImport } from './routes/api/bookmarks.ask'
import { Route as ApiBookmarkFoldersRssBulkRouteImport } from './routes/api/bookmark-folders.rss-bulk'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppTermsRouteImport } from './routes/_auth/app/terms'
import { Route as AuthAppProfileRouteImport } from './routes/_auth/app/profile'
import { Route as AuthAppLearnRouteImport } from './routes/_auth/app/learn'
import { Route as AuthAppHelpRouteImport } from './routes/_auth/app/help'
import { Route as AuthAppFeedsRouteImport } from './routes/_auth/app/feeds'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksRoute = ApiBookmarksRouteImport.update({
  id: '/api/bookmarks',
  path: '/api/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarkFoldersRoute = ApiBookmarkFoldersRouteImport.update({
  id: '/api/bookmark-folders',
  path: '/api/bookmark-folders',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiXConnectRoute = ApiXConnectRouteImport.update({
  id: '/api/x/connect',
  path: '/api/x/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXCallbackRoute = ApiXCallbackRouteImport.update({
  id: '/api/x/callback',
  path: '/api/x/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXBookmarksRoute = ApiXBookmarksRouteImport.update({
  id: '/api/x/bookmarks',
  path: '/api/x/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubStarsRoute = ApiGithubStarsRouteImport.update({
  id: '/api/github/stars',
  path: '/api/github/stars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReposRoute = ApiGithubReposRouteImport.update({
  id: '/api/github/repos',
  path: '/api/github/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubItemsRoute = ApiGithubItemsRouteImport.update({
  id: '/api/github/items',
  path: '/api/github/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksSearchRoute = ApiBookmarksSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiBookmarksRoute,
} as any)
const ApiBookmarksAskRoute = ApiBookmarksAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => ApiBookmarksRoute,
} as any)
const ApiBookmarkFoldersRssBulkRoute =
  ApiBookmarkFoldersRssBulkRouteImport.update({
    id: '/rss-bulk',
    path: '/rss-bulk',
    getParentRoute: () => ApiBookmarkFoldersRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppTermsRoute = AuthAppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppProfileRoute = AuthAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppLearnRoute = AuthAppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppHelpRoute = AuthAppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppFeedsRoute = AuthAppFeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => AuthAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/api/bookmark-folders': typeof ApiBookmarkFoldersRouteWithChildren
  '/api/bookmarks': typeof ApiBookmarksRouteWithChildren
  '/api/inngest': typeof ApiInngestRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/app/feeds': typeof AuthAppFeedsRoute
  '/app/help': typeof AuthAppHelpRoute
  '/app/learn': typeof AuthAppLearnRoute
  '/app/profile': typeof AuthAppProfileRoute
  '/app/terms': typeof AuthAppTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmark-folders/rss-bulk': typeof ApiBookmarkFoldersRssBulkRoute
  '/api/bookmarks/ask': typeof ApiBookmarksAskRoute
  '/api/bookmarks/search': typeof ApiBookmarksSearchRoute
  '/api/github/items': typeof ApiGithubItemsRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/github/stars': typeof ApiGithubStarsRoute
  '/api/x/bookmarks': typeof ApiXBookmarksRoute
  '/api/x/callback': typeof ApiXCallbackRoute
  '/api/x/connect': typeof ApiXConnectRoute
  '/app/': typeof AuthAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/api/bookmark-folders': typeof ApiBookmarkFoldersRouteWithChildren
  '/api/bookmarks': typeof ApiBookmarksRouteWithChildren
  '/api/inngest': typeof ApiInngestRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/app/feeds': typeof AuthAppFeedsRoute
  '/app/help': typeof AuthAppHelpRoute
  '/app/learn': typeof AuthAppLearnRoute
  '/app/profile': typeof AuthAppProfileRoute
  '/app/terms': typeof AuthAppTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmark-folders/rss-bulk': typeof ApiBookmarkFoldersRssBulkRoute
  '/api/bookmarks/ask': typeof ApiBookmarksAskRoute
  '/api/bookmarks/search': typeof ApiBookmarksSearchRoute
  '/api/github/items': typeof ApiGithubItemsRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/github/stars': typeof ApiGithubStarsRoute
  '/api/x/bookmarks': typeof ApiXBookmarksRoute
  '/api/x/callback': typeof ApiXCallbackRoute
  '/api/x/connect': typeof ApiXConnectRoute
  '/app': typeof AuthAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/terms': typeof TermsRoute
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/api/bookmark-folders': typeof ApiBookmarkFoldersRouteWithChildren
  '/api/bookmarks': typeof ApiBookmarksRouteWithChildren
  '/api/inngest': typeof ApiInngestRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/_auth/app/feeds': typeof AuthAppFeedsRoute
  '/_auth/app/help': typeof AuthAppHelpRoute
  '/_auth/app/learn': typeof AuthAppLearnRoute
  '/_auth/app/profile': typeof AuthAppProfileRoute
  '/_auth/app/terms': typeof AuthAppTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmark-folders/rss-bulk': typeof ApiBookmarkFoldersRssBulkRoute
  '/api/bookmarks/ask': typeof ApiBookmarksAskRoute
  '/api/bookmarks/search': typeof ApiBookmarksSearchRoute
  '/api/github/items': typeof ApiGithubItemsRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/github/stars': typeof ApiGithubStarsRoute
  '/api/x/bookmarks': typeof ApiXBookmarksRoute
  '/api/x/callback': typeof ApiXCallbackRoute
  '/api/x/connect': typeof ApiXConnectRoute
  '/_auth/app/': typeof AuthAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/terms'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/bookmark-folders'
    | '/api/bookmarks'
    | '/api/inngest'
    | '/api/profile'
    | '/api/uploadthing'
    | '/app/feeds'
    | '/app/help'
    | '/app/learn'
    | '/app/profile'
    | '/app/terms'
    | '/api/auth/$'
    | '/api/bookmark-folders/rss-bulk'
    | '/api/bookmarks/ask'
    | '/api/bookmarks/search'
    | '/api/github/items'
    | '/api/github/repos'
    | '/api/github/stars'
    | '/api/x/bookmarks'
    | '/api/x/callback'
    | '/api/x/connect'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terms'
    | '/login'
    | '/signup'
    | '/api/bookmark-folders'
    | '/api/bookmarks'
    | '/api/inngest'
    | '/api/profile'
    | '/api/uploadthing'
    | '/app/feeds'
    | '/app/help'
    | '/app/learn'
    | '/app/profile'
    | '/app/terms'
    | '/api/auth/$'
    | '/api/bookmark-folders/rss-bulk'
    | '/api/bookmarks/ask'
    | '/api/bookmarks/search'
    | '/api/github/items'
    | '/api/github/repos'
    | '/api/github/stars'
    | '/api/x/bookmarks'
    | '/api/x/callback'
    | '/api/x/connect'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/terms'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/signup'
    | '/api/bookmark-folders'
    | '/api/bookmarks'
    | '/api/inngest'
    | '/api/profile'
    | '/api/uploadthing'
    | '/_auth/app/feeds'
    | '/_auth/app/help'
    | '/_auth/app/learn'
    | '/_auth/app/profile'
    | '/_auth/app/terms'
    | '/api/auth/$'
    | '/api/bookmark-folders/rss-bulk'
    | '/api/bookmarks/ask'
    | '/api/bookmarks/search'
    | '/api/github/items'
    | '/api/github/repos'
    | '/api/github/stars'
    | '/api/x/bookmarks'
    | '/api/x/callback'
    | '/api/x/connect'
    | '/_auth/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  TermsRoute: typeof TermsRoute
  ApiBookmarkFoldersRoute: typeof ApiBookmarkFoldersRouteWithChildren
  ApiBookmarksRoute: typeof ApiBookmarksRouteWithChildren
  ApiInngestRoute: typeof ApiInngestRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubItemsRoute: typeof ApiGithubItemsRoute
  ApiGithubReposRoute: typeof ApiGithubReposRoute
  ApiGithubStarsRoute: typeof ApiGithubStarsRoute
  ApiXBookmarksRoute: typeof ApiXBookmarksRoute
  ApiXCallbackRoute: typeof ApiXCallbackRoute
  ApiXConnectRoute: typeof ApiXConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks': {
      id: '/api/bookmarks'
      path: '/api/bookmarks'
      fullPath: '/api/bookmarks'
      preLoaderRoute: typeof ApiBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmark-folders': {
      id: '/api/bookmark-folders'
      path: '/api/bookmark-folders'
      fullPath: '/api/bookmark-folders'
      preLoaderRoute: typeof ApiBookmarkFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/x/connect': {
      id: '/api/x/connect'
      path: '/api/x/connect'
      fullPath: '/api/x/connect'
      preLoaderRoute: typeof ApiXConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x/callback': {
      id: '/api/x/callback'
      path: '/api/x/callback'
      fullPath: '/api/x/callback'
      preLoaderRoute: typeof ApiXCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x/bookmarks': {
      id: '/api/x/bookmarks'
      path: '/api/x/bookmarks'
      fullPath: '/api/x/bookmarks'
      preLoaderRoute: typeof ApiXBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/stars': {
      id: '/api/github/stars'
      path: '/api/github/stars'
      fullPath: '/api/github/stars'
      preLoaderRoute: typeof ApiGithubStarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repos': {
      id: '/api/github/repos'
      path: '/api/github/repos'
      fullPath: '/api/github/repos'
      preLoaderRoute: typeof ApiGithubReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/items': {
      id: '/api/github/items'
      path: '/api/github/items'
      fullPath: '/api/github/items'
      preLoaderRoute: typeof ApiGithubItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks/search': {
      id: '/api/bookmarks/search'
      path: '/search'
      fullPath: '/api/bookmarks/search'
      preLoaderRoute: typeof ApiBookmarksSearchRouteImport
      parentRoute: typeof ApiBookmarksRoute
    }
    '/api/bookmarks/ask': {
      id: '/api/bookmarks/ask'
      path: '/ask'
      fullPath: '/api/bookmarks/ask'
      preLoaderRoute: typeof ApiBookmarksAskRouteImport
      parentRoute: typeof ApiBookmarksRoute
    }
    '/api/bookmark-folders/rss-bulk': {
      id: '/api/bookmark-folders/rss-bulk'
      path: '/rss-bulk'
      fullPath: '/api/bookmark-folders/rss-bulk'
      preLoaderRoute: typeof ApiBookmarkFoldersRssBulkRouteImport
      parentRoute: typeof ApiBookmarkFoldersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/terms': {
      id: '/_auth/app/terms'
      path: '/terms'
      fullPath: '/app/terms'
      preLoaderRoute: typeof AuthAppTermsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/profile': {
      id: '/_auth/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthAppProfileRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/learn': {
      id: '/_auth/app/learn'
      path: '/learn'
      fullPath: '/app/learn'
      preLoaderRoute: typeof AuthAppLearnRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/help': {
      id: '/_auth/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AuthAppHelpRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/feeds': {
      id: '/_auth/app/feeds'
      path: '/feeds'
      fullPath: '/app/feeds'
      preLoaderRoute: typeof AuthAppFeedsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppFeedsRoute: typeof AuthAppFeedsRoute
  AuthAppHelpRoute: typeof AuthAppHelpRoute
  AuthAppLearnRoute: typeof AuthAppLearnRoute
  AuthAppProfileRoute: typeof AuthAppProfileRoute
  AuthAppTermsRoute: typeof AuthAppTermsRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppFeedsRoute: AuthAppFeedsRoute,
  AuthAppHelpRoute: AuthAppHelpRoute,
  AuthAppLearnRoute: AuthAppLearnRoute,
  AuthAppProfileRoute: AuthAppProfileRoute,
  AuthAppTermsRoute: AuthAppTermsRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface ApiBookmarkFoldersRouteChildren {
  ApiBookmarkFoldersRssBulkRoute: typeof ApiBookmarkFoldersRssBulkRoute
}

const ApiBookmarkFoldersRouteChildren: ApiBookmarkFoldersRouteChildren = {
  ApiBookmarkFoldersRssBulkRoute: ApiBookmarkFoldersRssBulkRoute,
}

const ApiBookmarkFoldersRouteWithChildren =
  ApiBookmarkFoldersRoute._addFileChildren(ApiBookmarkFoldersRouteChildren)

interface ApiBookmarksRouteChildren {
  ApiBookmarksAskRoute: typeof ApiBookmarksAskRoute
  ApiBookmarksSearchRoute: typeof ApiBookmarksSearchRoute
}

const ApiBookmarksRouteChildren: ApiBookmarksRouteChildren = {
  ApiBookmarksAskRoute: ApiBookmarksAskRoute,
  ApiBookmarksSearchRoute: ApiBookmarksSearchRoute,
}

const ApiBookmarksRouteWithChildren = ApiBookmarksRoute._addFileChildren(
  ApiBookmarksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  TermsRoute: TermsRoute,
  ApiBookmarkFoldersRoute: ApiBookmarkFoldersRouteWithChildren,
  ApiBookmarksRoute: ApiBookmarksRouteWithChildren,
  ApiInngestRoute: ApiInngestRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubItemsRoute: ApiGithubItemsRoute,
  ApiGithubReposRoute: ApiGithubReposRoute,
  ApiGithubStarsRoute: ApiGithubStarsRoute,
  ApiXBookmarksRoute: ApiXBookmarksRoute,
  ApiXCallbackRoute: ApiXCallbackRoute,
  ApiXConnectRoute: ApiXConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
