/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ApiBookmarksRouteImport } from './routes/api/bookmarks'
import { Route as ApiBookmarkFoldersRouteImport } from './routes/api/bookmark-folders'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiBookmarksSearchRouteImport } from './routes/api/bookmarks.search'
import { Route as ApiBookmarksAskRouteImport } from './routes/api/bookmarks.ask'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksRoute = ApiBookmarksRouteImport.update({
  id: '/api/bookmarks',
  path: '/api/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarkFoldersRoute = ApiBookmarkFoldersRouteImport.update({
  id: '/api/bookmark-folders',
  path: '/api/bookmark-folders',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiBookmarksSearchRoute = ApiBookmarksSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiBookmarksRoute,
} as any)
const ApiBookmarksAskRoute = ApiBookmarksAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => ApiBookmarksRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/api/bookmark-folders': typeof ApiBookmarkFoldersRoute
  '/api/bookmarks': typeof ApiBookmarksRouteWithChildren
  '/api/inngest': typeof ApiInngestRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmarks/ask': typeof ApiBookmarksAskRoute
  '/api/bookmarks/search': typeof ApiBookmarksSearchRoute
  '/app/': typeof AuthAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/api/bookmark-folders': typeof ApiBookmarkFoldersRoute
  '/api/bookmarks': typeof ApiBookmarksRouteWithChildren
  '/api/inngest': typeof ApiInngestRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmarks/ask': typeof ApiBookmarksAskRoute
  '/api/bookmarks/search': typeof ApiBookmarksSearchRoute
  '/app': typeof AuthAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/api/bookmark-folders': typeof ApiBookmarkFoldersRoute
  '/api/bookmarks': typeof ApiBookmarksRouteWithChildren
  '/api/inngest': typeof ApiInngestRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmarks/ask': typeof ApiBookmarksAskRoute
  '/api/bookmarks/search': typeof ApiBookmarksSearchRoute
  '/_auth/app/': typeof AuthAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/bookmark-folders'
    | '/api/bookmarks'
    | '/api/inngest'
    | '/api/uploadthing'
    | '/api/auth/$'
    | '/api/bookmarks/ask'
    | '/api/bookmarks/search'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/bookmark-folders'
    | '/api/bookmarks'
    | '/api/inngest'
    | '/api/uploadthing'
    | '/api/auth/$'
    | '/api/bookmarks/ask'
    | '/api/bookmarks/search'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/signup'
    | '/api/bookmark-folders'
    | '/api/bookmarks'
    | '/api/inngest'
    | '/api/uploadthing'
    | '/api/auth/$'
    | '/api/bookmarks/ask'
    | '/api/bookmarks/search'
    | '/_auth/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiBookmarkFoldersRoute: typeof ApiBookmarkFoldersRoute
  ApiBookmarksRoute: typeof ApiBookmarksRouteWithChildren
  ApiInngestRoute: typeof ApiInngestRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks': {
      id: '/api/bookmarks'
      path: '/api/bookmarks'
      fullPath: '/api/bookmarks'
      preLoaderRoute: typeof ApiBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmark-folders': {
      id: '/api/bookmark-folders'
      path: '/api/bookmark-folders'
      fullPath: '/api/bookmark-folders'
      preLoaderRoute: typeof ApiBookmarkFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/bookmarks/search': {
      id: '/api/bookmarks/search'
      path: '/search'
      fullPath: '/api/bookmarks/search'
      preLoaderRoute: typeof ApiBookmarksSearchRouteImport
      parentRoute: typeof ApiBookmarksRoute
    }
    '/api/bookmarks/ask': {
      id: '/api/bookmarks/ask'
      path: '/ask'
      fullPath: '/api/bookmarks/ask'
      preLoaderRoute: typeof ApiBookmarksAskRouteImport
      parentRoute: typeof ApiBookmarksRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface ApiBookmarksRouteChildren {
  ApiBookmarksAskRoute: typeof ApiBookmarksAskRoute
  ApiBookmarksSearchRoute: typeof ApiBookmarksSearchRoute
}

const ApiBookmarksRouteChildren: ApiBookmarksRouteChildren = {
  ApiBookmarksAskRoute: ApiBookmarksAskRoute,
  ApiBookmarksSearchRoute: ApiBookmarksSearchRoute,
}

const ApiBookmarksRouteWithChildren = ApiBookmarksRoute._addFileChildren(
  ApiBookmarksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiBookmarkFoldersRoute: ApiBookmarkFoldersRoute,
  ApiBookmarksRoute: ApiBookmarksRouteWithChildren,
  ApiInngestRoute: ApiInngestRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
